# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  julia-17-release-x86_64-darwin = {
    pname = "julia-17-release-x86_64-darwin";
    version = "1.7.3-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.7/julia-1.7.3-mac64.dmg";
      sha256 = "sha256-Z3mewGz1e8qAqKHG5aFwSF07/ARhshdpmwcw2jfQZW8=";
    };
  };
  julia-17-release-x86_64-linux = {
    pname = "julia-17-release-x86_64-linux";
    version = "1.7.3-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz";
      sha256 = "sha256-my9PoS2StNzF0R3Gb7EYxHaBp209+NoGTMl1c/L1xzk=";
    };
  };
  julia-18-release-aarch64-darwin = {
    pname = "julia-18-release-aarch64-darwin";
    version = "1.8.5-macaarch64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/aarch64/1.8/julia-1.8.5-macaarch64.dmg";
      sha256 = "sha256-f2ojpKHYZPaeZbFUL9PRzzJNWckirEOASxugd7nMR10=";
    };
  };
  julia-18-release-aarch64-linux = {
    pname = "julia-18-release-aarch64-linux";
    version = "1.8.5-linux-aarch64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/aarch64/1.8/julia-1.8.5-linux-aarch64.tar.gz";
      sha256 = "sha256-ofY3tExx6pvJbXw+80dyTAVKHlInuYCt6/wzWZ5RU6Q=";
    };
  };
  julia-18-release-x86_64-darwin = {
    pname = "julia-18-release-x86_64-darwin";
    version = "1.8.5-mac64.dmg";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/mac/x64/1.8/julia-1.8.5-mac64.dmg";
      sha256 = "sha256-Iq/V4oqKgJ3HvgvJnPSRORoxr1ZpsXPPMxjkMydBSNs=";
    };
  };
  julia-18-release-x86_64-linux = {
    pname = "julia-18-release-x86_64-linux";
    version = "1.8.5-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.5-linux-x86_64.tar.gz";
      sha256 = "sha256-5xokgW6P6dX0gHZky7tCc49aqf4FOX01yB1MXWSbnQU=";
    };
  };
  julia-nightly-aarch64-darwin = {
    pname = "julia-nightly-aarch64-darwin";
    version = "julia-latest-macos-aarch64.dmg";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/macos/aarch64/julia-latest-macos-aarch64.dmg";
      sha256 = "sha256-9Yt5YydHEiBvJT89fT5hX49ZKrLaGH5qjf3qoAuPBj8=";
    };
  };
  julia-nightly-aarch64-linux = {
    pname = "julia-nightly-aarch64-linux";
    version = "julia-latest-linux-aarch64.tar.gz";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/linux/aarch64/julia-latest-linux-aarch64.tar.gz";
      sha256 = "sha256-takwlIe62lyCnTBKAY0rZyxUb9zxeuZShrZW0whaU5Y=";
    };
  };
  julia-nightly-x86_64-darwin = {
    pname = "julia-nightly-x86_64-darwin";
    version = "julia-latest-macos-x86_64.dmg";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/macos/x86_64/julia-latest-macos-x86_64.dmg";
      sha256 = "sha256-YwquvmK53N9opPVgGR1sERBg82oip6BN4lxtnVH5nZo=";
    };
  };
  julia-nightly-x86_64-linux = {
    pname = "julia-nightly-x86_64-linux";
    version = "julia-latest-linux-x86_64.tar.gz";
    src = fetchurl {
      url = "https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz";
      sha256 = "sha256-/cgVn3vIj92uNLuSKwTVylfzcM9FOAFIbA5bIYMAqE4=";
    };
  };
}
